### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by hhhhzs666** [ai-systems/hybrid_autoregressive_inference#1]
hello
If the corpus size is 170m, how to modify the process? 
bm25_fit, extract_chains.py is very slow

thanks

**Comment by mValentino91** [comment]
Hi,

Thanks for your message.

Do you mean 170 Millions facts? 

For the bm25 fit I would suggest to employ tools optimised for sparse text retrieval such as ElasticSearch.

Regarding the extract chains part, you could try to parallelize the preprocessing on large knowledge bases using multiple threads.

Best regards
 
Marco Valentino

**Comment by hhhhzs666** [comment]
yes ,170 Millions facts

and the trained sparse_model don't work in extract_chains.py,  I think the reason is RS.compute() has no effect

Thank you for your advice

**Comment by mValentino91** [comment]
If you do not use the fit function then the compute function will have no effect.

Keep in mind that extract_chains.py is a preprocessing step that is used to construct the training set for the dense retrieval model. My question is, do you really need to consider all 170 Millions facts to construct the training set?

Maybe you can use just a subset of facts and make the chain extraction more efficient, then use tools such as ElasticSearch at inference time for the sparse retrieval component. The dense retrieval with faiss should scale on larger kbs and you can always play with the faiss parameters to make retrieval faster.

**Comment by hhhhzs666** [comment]
good idea ,extract_chains.py is useful

I will use a subset of facts and make the chain extraction

Thank you for your advice
