### ISSUE TITLE
BM25 compute

### ISSUE THREAD

**Issue by hhhhzs666** [ai-systems/hybrid_autoregressive_inference#2]
Hello, I noticed that in your code BM25 is calculated by obtaining a feature vector from the BM25 score of each word in the sentence.

Does calculating the similarity between feature vectors work as well as traditional BM25 scores?

Thanks

**Comment by mValentino91** [comment]
Hi,

Thanks for your message!

In the paper we use bm25 to compute sparse vector representations (similarity to tf-idf) and combine it with cosine similarity.

This approach works similarity to traditional bm25 but thanks to cosine similarity it produces a bounded scoring function (traditional bm25 is not bounded) which can more easily be combined with other models (i.e. in our case dense retrieval).

Hope this answer the question!
